/*
  Warnings:

  - You are about to drop the column `address` on the `Users` table. All the data in the column will be lost.
  - You are about to drop the column `paid` on the `Users` table. All the data in the column will be lost.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_Users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "cartype" STRING,
    "carplate" STRING,
    "date" TIMESTAMP(3),
    "time" TIMESTAMP(3),
    "payment_type" STRING,
    "tips" FLOAT8,

    CONSTRAINT "Users_pkey" PRIMARY KEY ("id")
);
DROP INDEX "Users_address_key";
DROP TABLE "Users" CASCADE;
ALTER TABLE "_prisma_new_Users" RENAME TO "Users";
