/*
  Warnings:

  - You are about to drop the `Users` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "Users";

-- CreateTable
CREATE TABLE "User" (
    "userid" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "password" STRING NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("userid")
);

-- CreateTable
CREATE TABLE "Cars" (
    "carid" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "cartype" STRING,
    "carplate" STRING,
    "date" TIMESTAMP(3),
    "time" TIMESTAMP(3),
    "payment_type" STRING,
    "tips" FLOAT8,

    CONSTRAINT "Cars_pkey" PRIMARY KEY ("carid")
);
